# Generated by Django — ExpensePayment for multi-payer expenses

from django.db import migrations, models
import django.db.models.deletion


def backfill_payments_from_paid_by(apps, schema_editor):
    Expense = apps.get_model("expenses", "Expense")
    ExpensePayment = apps.get_model("expenses", "ExpensePayment")
    for expense in Expense.objects.all():
        if ExpensePayment.objects.filter(expense_id=expense.pk).exists():
            continue
        ExpensePayment.objects.create(
            expense_id=expense.pk,
            user_id=expense.paid_by_id,
            amount=expense.amount,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_group_currency_alter_group_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpensePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="expenses.expense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_payments",
                        to="expenses.user",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="expensepayment",
            unique_together={("expense", "user")},
        ),
        migrations.RunPython(
            backfill_payments_from_paid_by,
            migrations.RunPython.noop,
        ),
    ]
